### ISSUE TITLE
Target submission issues

### ISSUE THREAD

**Issue by len0rd** [BYU-AUVSI/imaging#23]
GUI is in the final stretch (at least for initial release ;) Almost ready to merge! Couple issues while running it today that we should look into:

- [ ] I'm unable to press "Submit Target" without specifying specific classifications to use. I think this was the exception for it:

```
Traceback (most recent call last):
  File "/anaconda3/envs/auvspy/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "client_gui.py", line 1889, in submitTarget
    submission = client_rest.TargetSubmission(self.submit_crop_id,self.submit_orientation,self.submit_bg_color,self.submit_alpha_color,self.submit_desc)
AttributeError: 'GuiClass' object has no attribute 'submit_orientation'
```

- [x] I wasn't able to delete all classifications for a target. Idk if we want to support this functionality.. (?). But maybe there's a single classification that is binned as its own target that just isn't good and we want to delete it and its target. Exception was this:

```
Traceback (most recent call last):
  File "/anaconda3/envs/auvspy/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "client_gui.py", line 2137, in deleteClassification1
    classification_id = self.pendingList[self.t3_current_target-1][0].class_id
TypeError: 'NoneType' object is not subscriptable
```

**Comment by betaBison** [comment]
@len0rd Pushed changes to fix the above bugs ... (hopefully)

**Comment by len0rd** [comment]
I think that did it! thanks
