### ISSUE TITLE
Target geolocation averaging should be less dumb

### ISSUE THREAD

**Issue by len0rd** [BYU-AUVSI/imaging#36]
https://github.com/BYU-AUVSI/imaging/blob/d7b89bb3b1a31a0456e9f7f29d555eca725ebbce/server/src/dao/classification_dao.py#L553

- You should not add values `== 0` to `ttl`
- (L558) `ttl` should be divided by the number of values you add to it (not necessarily `len(classifications)`)

**Comment by benjjensen** [comment]
The code has been updated as advised.
